<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="GOD-PC-PC" name="day4.DuplicateLead" tests="1" failures="0" timestamp="25 Feb 2017 08:05:41 GMT" time="0.000" errors="1">
  <testcase name="executeDuplicateLeadTestCAse" time="0.000" classname="day4.DuplicateLead">
    <error type="java.lang.Throwable" message="Method DuplicateLead.executeDuplicateLeadTestCAse()[pri:0, instance:day4.DuplicateLead@10f6bfd] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method DuplicateLead.executeDuplicateLeadTestCAse()[pri:0, instance:day4.DuplicateLead@10f6bfd] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
    </error>
  </testcase> <!-- executeDuplicateLeadTestCAse -->
</testsuite> <!-- day4.DuplicateLead -->
